web_server:
  bind: 0.0.0.0
  port: 3539

schedules:
  - tasks: [ pterclub, totheglory, leaguehd, rss_download ]
    interval:
      minutes: 1

  - tasks: [ reseed, resume, delete, modify, clean ]
    interval:
      minutes: 5

  - tasks: [ opencd, springsunday ]
    interval:
      minutes: 10

  - tasks: [ sign_in, warner ]
    schedule:
      hour: 8-23/1

variables:
  headers:
    user_agent: 'xxxxxxxx'
  via: &via_setting
    - wechat_work:
        corp_id: 'xxxxxxxx'
        corp_secret: 'xxxxxxxx'
        agent_id: 'xxxxxxxx'
        to_user: 'xxxxxxxx'
    - telegram:
        bot_token: xxxxxxxx
        recipients:
          - username: 'xxxxxxxx'

templates:
  from_qbittorrent_template:
    from_qbittorrent_mod: &qbittorrent_setting
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: xxxxxxxx
      password: xxxxxxxx

  qbittorrent_base_template:
    qbittorrent_mod: *qbittorrent_setting

  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: 8388608
          reject_on_dl_speed: 6291456
          category: Rss
          autoTMM: yes

  qbittorrent_resume_template:
    qbittorrent_mod:
      action:
        resume:
          recheck_torrents: yes

  qbittorrent_pause_template:
    qbittorrent_mod:
      action:
        pause: yes

  qbittorrent_delete_keeper_template:
    qbittorrent_mod:
      action:
        remove:
          keeper:
            check_reseed:
              - chdbits
              - totheglory
              - m-team
              - open
              - pterclub
              - springsunday
              - ourbits
              - hdsky
              - keepfrds
              - leaguehd
            delete_files: yes
            keep_disk_space: 10
            dl_limit_on_succeeded: 0
            alt_dl_limit_on_succeeded: 8388608
            dl_limit_interval: 900
            #show_entry: 633645aa28a4aa48e8b7d2ac618fe691e81df30f

  qbittorrent_delete_cleaner_template:
    qbittorrent_mod:
      action:
        remove:
          cleaner:
            delete_files: yes

  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          tag_by_tracker: yes
          #replace_trackers:
          #'http://tracker.pterclub.com/announce?passkey=xxxxxxxx': 'https://tracker.pterclub.com/announce?passkey=xxxxxxxx'

tasks:
  pterclub:
    rss:
      url: https://pterclub.com/torrentrss.php?rows=10&cat413=1&tag_internal=yes&isize=1&linktype=dl&passkey=xxxxxxxx
      all_entries: no
      other_fields:
        - link
    no_entries_ok: yes
    if:
      - size > 1024 * 1024 and size < 20 * 1024 *1024: accept
    notify:
      entries:
        message: "Title: {{title}}\nLink: {{link}}"
        via: *via_setting
    qbittorrent_mod:
      action:
        add:
          category: PTer
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  totheglory:
    rss:
      url: https://totheglory.im/putrss.php?par=xxxxxxxx
      all_entries: no
    no_entries_ok: yes
    regexp:
      accept:
        - TTG
        - Wiki
      from: title
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  springsunday:
    html_rss:
      url: https://springsunday.net/torrents.php?incldead=0&spstate=4&pick=0&inclbookmarked=0&exclusive=0&search=&search_area=0&search_mode=0&sort=8&type=desc
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '.torrents > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        leechers:
          element_selector: 'td:nth-child(8)'
          attribute: textContent
    no_entries_ok: yes
    if:
      - leechers|int > 4: accept
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  hdhome:
    html_rss:
      url: https://hdhome.org/torrents.php?incldead=1&spstate=4&inclbookmarked=0&search=&search_area=0&search_mode=0
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '#torrenttable > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        leecher:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
        hr:
          element_selector: 'img.hitandrun'
          attribute: alt
    no_entries_ok: yes
    if:
      - leecher|int > 1: accept
      - hr: reject
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template


  opencd:
    html_rss:
      url: https://open.cd/torrents.php?spstate=2&seeders=3&sort=7&type=asc
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'div[style="padding-bottom: 5px"] > img'
          attribute: alt
        progress:
          element_selector: '.progress_completed'
          attribute: class
    no_entries_ok: yes
    if:
      - promotion in ['Free', '2X Free']: accept
      - "progress and 'progress_completed' not in progress": reject
      - size > 100*1024*1024*1024: reject
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  leaguehd:
    inputs:
      - rss:
          url: https://leaguehd.com/torrentrss.php?rows=10&cat500=1&cat409=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
    no_entries_ok: yes
    accept_all: yes
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  rss_download:
    inputs:
      - rss:
          url: https://www.tjupt.org/torrentrss.php?rows=10&official=1&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://pt.m-team.cc/torrentrss.php?https=1&rows=10&tea9=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://hdsky.me/torrentrss.php?rows=10&tea6=1&tea1=1&tea28=1&tea9=1&tea31=1&tea18=1&tea22=1&tea34=1&tea35=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://springsunday.net/torrentrss.php?rows=10&tea1=1&tea9=1&isize=1&https=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://ourbits.club/torrentrss.php?rows=10&tea1=1&isize=1&passkey=xxxxxxxx&https=1&linktype=dl
          all_entries: no
      - rss:
          url: https://pt.keepfrds.com/torrentrss.php?rows=10&tea6=1&tea3=1&tea8=1&tea9=1&tea10=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://open.cd/torrentrss.php?rows=10&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://chdbits.co/torrentrss.php?rows=10&tea14=1&tea13=1&tea1=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://leaguehd.com/torrentrss.php?rows=10&cat405=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
    no_entries_ok: yes
    accept_all: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  reseed:
    priority: 1
    plugin_priority:
      from_qbittorrent_mod: 250
      iyuu_auto_reseed: 240
    iyuu_auto_reseed:
      iyuu: xxxxxxxx
      passkeys:
        1ptba: xxxxxxxx
        52pt: xxxxxxxx
        beitai: xxxxxxxx
        brobits: xxxxxxxx
        btschool: xxxxxxxx
        chdbits: xxxxxxxx
        dicmusic:
          authkey: xxxxxxxx
          torrent_pass: xxxxxxxx
        discfan: xxxxxxxx
        eastgame: xxxxxxxx
        et8: xxxxxxxx
        hd-torrents: xxxxxxxx
        haidan: xxxxxxxx
        hdarea: xxxxxxxx
        hdbd: xxxxxxxx
        hdcity:
          headers:
            cookie: 'xxxxxxxx'
            user-agent: '{? headers.user_agent ?}'
        hddisk: xxxxxxxx
        hddolby: xxxxxxxx
        hdfans: xxxxxxxx
        hdhome: xxxxxxxx
        hdsky: xxxxxxxx
        hdstreet: xxxxxxxx
        hdtime: xxxxxxxx
        hdupt: xxxxxxxx
        hdzone: xxxxxxxx
        hitpt: xxxxxxxx
        joyhd: xxxxxxxx
        keepfrds: xxxxxxxx
        leaguehd: xxxxxxxx
        msg: xxxxxxxx
        m-team: xxxxxxxx
        nicept: xxxxxxxx
        nanyangpt: xxxxxxxx
        open: xxxxxxxx
        oshen: xxxxxxxx
        ourbits: xxxxxxxx
        pterclub: xxxxxxxx
        pthome: xxxxxxxx
        ptsbao: xxxxxxxx
        skyeysnow: xxxxxxxx
        soulvoice: xxxxxxxx
        springsunday: xxxxxxxx
        sjtu: xxxxxxxx
        tjupt: xxxxxxxx
        totheglory: xxxxxxxx
        yingk: xxxxxxxx
    accept_all: yes
    no_entries_ok: yes
    seen:
      fields:
        - url
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
          skip_checking: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      - from_qbittorrent_template

  resume:
    priority: 2
    disable: [ seen, seen_info_hash, retry_failed ]
    if:
      - qbittorrent_state == 'pausedUP' and qbittorrent_downloaded == 0 and qbittorrent_added_on > now - timedelta(hours=1): accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

  delete:
    priority: 3
    disable: [ seen, seen_info_hash, retry_failed ]
    if:
      - qbittorrent_category in ['Rss'] and qbittorrent_last_activity < now - timedelta(hours=2): accept
      - qbittorrent_state == 'missingFiles' or (qbittorrent_state in ['pausedDL'] and qbittorrent_completed == 0): accept
      - "'open' in qbittorrent_tags and (qbittorrent_seeding_time < 48*60*60 or qbittorrent_num_complete < 5) and not qbittorrent_state in ['pausedDL']": reject
    sort_by: qbittorrent_reseed_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template

  modify:
    priority: 4
    disable: [ seen, seen_info_hash, retry_failed ]
    accept_all: yes
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template

  clean:
    priority: 5
    disable: [ seen, seen_info_hash, retry_failed ]
    if:
      - qbittorrent_tracker_msg == 'torrent not registered with this tracker': accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_cleaner_template

  sign_in:
    auto_sign_in:
      user-agent: '{? headers.user_agent ?}'
      max_workers: 1
      aipocr:
        app_id: 'xxxxxxxx'
        api_key: 'xxxxxxxx'
        secret_key: 'xxxxxxxx'
      sites:
        qbittorrent:
          name: qbittorrent
          host: qbittorrent.example.com
          port: 443
          use_ssl: yes
          username: xxxxxxxx
          password: xxxxxxxx
        1ptba: 'xxxxxxxx'
        52pt: 'xxxxxxxx'
        avgv: 'xxxxxxxx'
        beitai: 'xxxxxxxx'
        btschool: 'xxxxxxxx'
        chdbits: 'xxxxxxxx'
        dhcmusic: 'xxxxxxxx'
        dicmusic: 'xxxxxxxx'
        discfan: 'xxxxxxxx'
        eastgame: 'xxxxxxxx'
        et8: 'xxxxxxxx'
        haidan: 'xxxxxxxx'
        hdarea: 'xxxxxxxx'
        hdatmos: 'xxxxxxxx'
        hdbd: 'xxxxxxxx'
        hdcity: 'xxxxxxxx'
        hddolby: 'xxxxxxxx'
        hddisk: 'xxxxxxxx'
        hdfans: 'xxxxxxxx'
        hdhome: 'xxxxxxxx'
        hdpost:
          login:
            usernameOrEmail: 'xxxxxxxx'
            password: 'xxxxxxxx'
        hdsky: 'xxxxxxxx'
        hdstreet: 'xxxxxxxx'
        hdtime: 'xxxxxxxx'
        hdupt: 'xxxxxxxx'
        hdzone: 'xxxxxxxx'
        hitpt: 'xxxxxxxx'
        joyhd: 'xxxxxxxx'
        keepfrds: 'xxxxxxxx'
        lbj007: 'xxxxxxxx'
        leaguehd: 'xxxxxxxx'
        m-team:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
            secret_key: 'xxxxxxxx'
        msg: 'xxxxxxxx'
        nicept: 'xxxxxxxx'
        nanyangpt: 'xxxxxxxx'
        open: 'xxxxxxxx'
        oshen: 'xxxxxxxx'
        ourbits:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
        pterclub: 'xxxxxxxx'
        pthome: 'xxxxxxxx'
        ptsbao: 'xxxxxxxx'
        skyey2:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
        soulvoice: 'xxxxxxxx'
        springsunday: 'xxxxxxxx'
        sjtu: 'xxxxxxxx'
        totheglory: 'xxxxxxxx'
        tjupt: 'xxxxxxxx'
        wenyuan: 'xxxxxxxx'
        yingk: 'xxxxxxxx'
        suannai: 'xxxxxxxx'
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: false
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }} Reason: {{entry.reason|d('unknown')}}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- for group in task.entries|groupby('task') %}
          {% for entry in group.list %}
          {%- if entry.messages|d('') %}
          Messages:
          {{ entry.title }} {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
        via:
          - wechat_work:
              corp_id: 'xxxxxxxx'
              corp_secret: 'xxxxxxxx'
              agent_id: 'xxxxxxxx'
              to_user: 'xxxxxxxx'
              image: 'details_report.png'
          - telegram:
              bot_token: xxxxxxxx
              recipients:
                - username: 'xxxxxxxx'

  warner:
    disable: [ seen, seen_info_hash, retry_failed ]
    from_qbittorrent_mod:
      server_state: 'qBittorrent Server State'
    if:
      - 'not server_state["flexget_connected"]': accept
      - 'server_state["dl_info_speed"] < 1048576': accept
      - 'server_state["up_info_speed"] < 1048576': accept
      - 'server_state["free_space_on_disk"] < 5368709120': accept
    template:
      - from_qbittorrent_template
    notify:
      entries:
        message: |+
          {{ time }}
          {{ title }}:
          {% if not server_state.flexget_connected -%}
          flexget_connected: False
          {%- else -%}
          dl_info_speed: {{(server_state['dl_info_speed']/1024/1024)|int}} MiB
          up_info_speed: {{(server_state['up_info_speed']/1024/1024)|int}} MiB
          free_space_on_disk: {{(server_state['free_space_on_disk']/1024/1024/1024)|int}} GiB
          {% endif %}
        via: *via_setting
