web_server:
  bind: 0.0.0.0
  port: 3539

templates:
  qbittorrent_base_template:
    qbittorrent_mod:
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: admin
      password: xxxxxxxxxx

  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: 4191304
          reject_on_dl_speed: 6291456
          category: Rss
          autoTMM: yes

  qbittorrent_resume_template:
    qbittorrent_mod:
      action:
        resume:
          recheck_torrents: yes

  qbittorrent_delete_template:
    qbittorrent_mod:
      action:
        remove:
          check_reseed:
            - totheglory
            - m-team
            - hdhome
            - open
            - pterclub
          delete_files: yes
          keep_disk_space: 10
          dl_limit_on_succeeded: 8388608
          dl_limit_interval: 900
          #show_entry: 633645aa28a4aa48e8b7d2ac618fe691e81df30f

  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          tag_by_tracker: yes

  from_qbittorrent_template:
    from_qbittorrent_mod:
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: admin
      password: xxxxxxxxxx

schedules:
  - tasks: [pterclub, hdhome, rss_download]
    interval:
      minutes: 1

  - tasks: [reseed, resume, delete, modify]
    interval:
      minutes: 5

  - tasks: [opencd]
    interval:
      minutes: 10

  - tasks: [sign_in, warner]
    schedule:
      hour: 8-23/1

tasks:
  pterclub:
    rss:
      url: https://pterclub.com/torrentrss.php?rows=10&cat413=1&tag_internal=yes&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      all_entries: no
      other_fields:
        - link
    no_entries_ok: yes
    if:
      - size > 1024 * 1024 and size < 20 * 1024 *1024: accept
    notify:
      entries:
        message: "Title: {{title}}\nLink: {{link}}"
        via:
          - wechat_work:
              corp_id: 'xxxxxxxxxxxx'
              corp_secret: 'xxxxxxxxxxxx'
              agent_id: 'xxxxxxxxxxxx'
              to_user: 'xxxxxxxxxxxx'
          - telegram:
              bot_token: xxxxxxxxxxxx
              recipients:
                - username: 'xxxxxxxxxxxx'
    qbittorrent_mod:
      action:
        add:
          category: PTer
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  hdhome:
    html_rss:
      url: https://hdhome.org/torrents.php?incldead=1&spstate=4&inclbookmarked=0&search=&search_area=0&search_mode=0
      headers:
        cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36'
      params: '&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      root_element_selector: '#torrenttable > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        leecher:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
        hr:
          element_selector: 'img.hitandrun'
          attribute: alt
    no_entries_ok: yes
    if:
      - leecher|int > 1: accept
      - hr: reject
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template


  opencd:
    html_rss:
      url: https://open.cd/torrents.php?spstate=2&seeders=3&sort=7&type=asc
      headers:
        cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36'
      params: '&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'div[style="padding-bottom: 5px"] > img'
          attribute: alt
        progress:
          element_selector: '.progress_completed'
          attribute: class
    no_entries_ok: yes
    if:
      - promotion in ['Free', '2X Free']: accept
      - "progress and 'progress_completed' not in progress": reject
      - size > 100*1024*1024*1024: reject
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  rss_download:
    inputs:
      - rss:
          url: https://hdhome.org/torrentrss.php?rows=10&tea1=1&tea12=1&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          all_entries: no
      - rss:
          url: https://www.tjupt.org/torrentrss.php?rows=10&isize=1&search=TJUPT&search_mode=1&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          all_entries: no
      - rss:
          url: https://pt.m-team.cc/torrentrss.php?https=1&rows=10&cat406=1&cat408=1&cat434=1&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          all_entries: no
    no_entries_ok: yes
    accept_all: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  reseed:
    priority: 1
    iyuu_auto_reseed:
      iyuu: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      passkeys:
        1ptba: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        52pt: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        beitai: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        brobits: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        btschool: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        discfan: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        eastgame: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        et8: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        haidan: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hdarea: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hdbd: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hddisk: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hddolby: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hdhome: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hdstreet: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hdtime: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        hdzone: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        joyhd: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        leaguehd: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        moecat: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        msg: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        m-team: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        nanyangpt: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        open: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        oshen: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        pterclub: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        pthome: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        ptsbao: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        skyeysnow: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        soulvoice: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tjupt: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        totheglory: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        yingk: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      qbittorrent_ressed:
        host: qbittorrent.example.com
        port: 443
        use_ssl: yes
        username: xxxxxxx
        password: xxxxxxxxxx
    accept_all: yes
    no_entries_ok: yes
    seen:
      fields:
        - url
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
          skip_checking: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  resume:
    priority: 2
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_state == 'pausedUP' and qbittorrent_downloaded == 0 and qbittorrent_added_on < now - timedelta(hours=1): accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

  delete:
    priority: 3
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_category in ['Rss'] and qbittorrent_last_activity < now - timedelta(hours=2): accept
      - qbittorrent_state == 'missingFiles' or (qbittorrent_state in ['pausedDL'] and qbittorrent_completed == 0): accept
      - "'open' in qbittorrent_tags and (qbittorrent_seeding_time < 48*60*60 or qbittorrent_num_complete < 5) and not qbittorrent_state in ['pausedDL']": reject
    sort_by: qbittorrent_reseed_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_template

  modify:
    priority: 4
    disable: [seen, seen_info_hash, retry_failed]
    accept_all: yes
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template

  sign_in:
    auto_sign_in:
      user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'
      command_executor: 'http://selenium-chrome:4444/wd/hub'
      aipocr_app_id: 'xxxxxx'
      aipocr_api_key: 'xxxxxx'
      aipocr_secret_key: 'xxxxxx'
      sites:
        1ptba:
          url: https://1ptba.com/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        52pt:
          url: https://52pt.site/bakatest.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: question
          succeed_regex: '连续.*天签到,获得.*点魔力值|今天已经签过到了\(已连续.*天签到\)'
          wrong_regex: '回答错误,失去 1 魔力值,这道题还会再考一次'
        avgv:
          url: http://avgv.cc/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        beitai:
          url: https://www.beitai.pt/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        btschool:
          url: https://pt.btschool.club/index.php?action=addbonus
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        crypt:
          url: http://www.crypt.pub/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        dicmusic:
          url: https://dicmusic.club/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          get_message: Gazelle
        discfan:
          url: https://discfan.net/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '這是您的第 .* 次簽到，已連續簽到 .* 天，本次簽到獲得 .* 個魔力值。|您今天已經簽到過了，請勿重複刷新。'
        eastgame:
          url: https://pt.eastgame.org/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        et8:
          url: https://et8.org/index.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        haidan:
          base_url: https://www.haidan.video/index.php
          url: https://www.haidan.video/signin.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '恭喜您,获得了\d*魔力值 !|(?<=value=")已经打卡(?=")'
        hdarea:
          base_url: https://www.hdarea.co/torrents.php
          url: https://www.hdarea.co/sign_in.php?action=sign_in
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: post
          data:
            fixed:
              action: 'sign_in'
          succeed_regex: '已连续签到.*天，此次签到您获得了.*魔力值奖励!|请不要重复签到哦！'
        hdbd:
          url: https://pt.hdbd.us/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        hddolby:
          url: https://www.hddolby.com/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        hddisk:
          url: https://hddisk.life/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        hdfans:
          url: https://hdfans.org/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        hdhome:
          url: https://hdhome.org/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        hdpost:
          url: https://hdpost.top/api/check
          login_url: https://hdpost.top/api/auth/signin
          login_data:
            usernameOrEmail: 'xxxxxxxxx'
            password: 'xxxxxxxxxxx'
          succeed_regex: '"keepDays":\d+'
        hdstreet:
          url: https://hdstreet.club/bakatest.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: question
          succeed_regex: '连续.*天签到,获得.*点魔力值|今天已经签过到了\(已连续.*天签到\)'
          wrong_regex: '回答错误,失去 1 魔力值,这道题还会再考一次'
        hdtime:
          url: https://hdtime.org/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        hdzone:
          url: http://hdzone.me/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        j99:
          url: https://pt.j99.info/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        joyhd:
          url: https://www.joyhd.net/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        lbj007:
          url: https://lbj007.com/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        leaguehd:
          url: https://leaguehd.com/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        m-team:
          url: https://pt.m-team.cc/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          message_url: https://pt.m-team.cc/messages.php?action=viewmailbox&box=-2
        moecat:
          url: https://moecat.best/bakatest.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          cf: yes
          method: question
          succeed_regex: '连续.*天签到,获得.*点魔力值|今天已经签过到了\(已连续.*天签到\)'
          wrong_regex: '回答错误,失去 1 魔力值,这道题还会再考一次'
        msg:
          url: https://pt.msg.vg/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        nanyangpt:
          url: https://nanyangpt.com/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        opencd:
          base_url: https://open.cd/
          url: https://open.cd/plugin_sign-in.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: code
          succeed_regex: '查看簽到記錄|{"state":"success","signindays":"\d+","integral":"\d+"}'
          wrong_regex: '验证码错误'
        oshen:
          url: http://www.oshen.win/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        pterclub:
          url: https://pterclub.com/attendance-ajax.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天。<\\\/p><p>本次签到获得 .* 克猫粮。|您今天已经签到过了，请勿重复刷新。'
        pthome:
          url: https://www.pthome.net/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        ptsbao:
          url: https://ptsbao.club/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        skyey2:
          url: https://www.skyey2.com/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          get_message: no
        soulvoice:
          url: https://pt.soulvoice.club/attendance.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          succeed_regex: '这是您的第 .* 次签到，已连续签到 .* 天，本次签到获得 .* 个魔力值。|您今天已经签到过了，请勿重复刷新。'
        totheglory:
          base_url: https://totheglory.im/
          url: https://totheglory.im/signed.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: post
          data:
            signed_timestamp: '(?<=signed_timestamp: ")\d{10}'
            signed_token: '(?<=signed_token: ").*(?="'
          succeed_regex: '<b style="color:green;">已签到</b>|您已连续签到.*天，奖励.*积分，明天继续签到将获得.*积分奖励。'
        tjupt:
          url: https://tjupt.org/
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        yingk:
          url: https://yingk.com/bakatest.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: question
          succeed_regex: '连续.*天签到,获得.*点魔力值|今天已经签过到了\(已连续.*天签到\)'
          wrong_regex: '回答错误,失去 1 魔力值,这道题还会再考一次'
        wenyuan:
          url: https://www.xn--7p0ar28b.xyz/bakatest.php
          cookie: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          method: question
          succeed_regex: '连续.*天签到,获得.*点魔力值|今天已经签过到了\(已连续.*天签到\)'
          wrong_regex: '回答错误,失去 1 魔力值,这道题还会再考一次'
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: false
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {% for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- if entry.messages|d('') %}
          Messages: {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {% for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} Reason: {{ entry.reason|d('unknown') }}
          {%- if entry.messages|d('') %}
          Messages: {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
        via:
          - wechat_work:
              corp_id: 'xxxxxxxxxxxx'
              corp_secret: 'xxxxxxxxxxxx'
              agent_id: 'xxxxxxxxxxxx'
              to_user: 'xxxxxxxxxxxx'
          - telegram:
              bot_token: xxxxxxxxxxxx
              recipients:
                - username: 'xxxxxxxxxxxx'

  warner:
    disable: [seen, seen_info_hash, retry_failed]
    from_qbittorrent_mod:
      server_state: yes
    if:
      - 'server_state["free_space_on_disk"] < 5242880': accept
    template:
      - from_qbittorrent_template
    notify:
      entries:
        message: "Title: {{title}}\nfree_space_on_disk: {{(server_state['free_space_on_disk']/1024/1024/1024)|int}} GiB"
        via:
          - wechat_work:
              corp_id: 'xxxxxxxxxxxx'
              corp_secret: 'xxxxxxxxxxxx'
              agent_id: 'xxxxxxxxxxxx'
              to_user: 'xxxxxxxxxxxx'
          - telegram:
              bot_token: xxxxxxxxxxxx
              recipients:
                - username: 'xxxxxxxxxxxx'