web_server:
  bind: 0.0.0.0
  port: 3539

variables:
  headers:
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36'

templates:
  from_qbittorrent_template:
    from_qbittorrent_mod:
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: xxxxxxxx
      password: xxxxxxxx

  qbittorrent_base_template:
    qbittorrent_mod:
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: xxxxxxxx
      password: xxxxxxxx

  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: 8388608
          reject_on_dl_speed: 6291456
          category: Rss
          autoTMM: yes

  qbittorrent_resume_template:
    qbittorrent_mod:
      action:
        resume:
          recheck_torrents: yes

  qbittorrent_delete_template:
    qbittorrent_mod:
      action:
        remove:
          check_reseed:
            - totheglory
            - m-team
            - hdhome
            - open
            - pterclub
            - springsunday
            - ourbits
            - hdsky
          delete_files: yes
          keep_disk_space: 10
          dl_limit_on_succeeded: 8388608
          dl_limit_interval: 900
          #show_entry: 633645aa28a4aa48e8b7d2ac618fe691e81df30f

  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          tag_by_tracker: yes

schedules:
  - tasks: [pterclub, rss_download]
    interval:
      minutes: 1

  - tasks: [reseed, resume, delete, modify]
    interval:
      minutes: 5

  - tasks: [opencd]
    interval:
      minutes: 10

  - tasks: [sign_in, warner]
    schedule:
      hour: 8-23/1

tasks:
  pterclub:
    rss:
      url: https://pterclub.com/torrentrss.php?rows=10&cat413=1&tag_internal=yes&isize=1&linktype=dl&passkey=xxxxxxxx
      all_entries: no
      other_fields:
        - link
    no_entries_ok: yes
    if:
      - size > 1024 * 1024 and size < 20 * 1024 *1024: accept
    notify:
      entries:
        message: "Title: {{title}}\nLink: {{link}}"
        via:
          - wechat_work:
              corp_id: 'xxxxxxxx'
              corp_secret: 'xxxxxxxx'
              agent_id: 'xxxxxxxx'
              to_user: 'xxxxxxxx'
          - telegram:
              bot_token: xxxxxxxx
              recipients:
                - username: 'xxxxxxxx'
    qbittorrent_mod:
      action:
        add:
          category: PTer
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  hdhome:
    html_rss:
      url: https://hdhome.org/torrents.php?incldead=1&spstate=4&inclbookmarked=0&search=&search_area=0&search_mode=0
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '#torrenttable > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        leecher:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
        hr:
          element_selector: 'img.hitandrun'
          attribute: alt
    no_entries_ok: yes
    if:
      - leecher|int > 1: accept
      - hr: reject
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template


  opencd:
    html_rss:
      url: https://open.cd/torrents.php?spstate=2&seeders=3&sort=7&type=asc
      headers:
        cookie: 'xxxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'div[style="padding-bottom: 5px"] > img'
          attribute: alt
        progress:
          element_selector: '.progress_completed'
          attribute: class
    no_entries_ok: yes
    if:
      - promotion in ['Free', '2X Free']: accept
      - "progress and 'progress_completed' not in progress": reject
      - size > 100*1024*1024*1024: reject
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  rss_download:
    inputs:
      - rss:
          url: https://hdhome.org/torrentrss.php?rows=10&tea1=1&tea12=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://www.tjupt.org/torrentrss.php?rows=10&official=1&passkey=xxxxxxxx1&linktype=dl
          all_entries: no
      - rss:
          url: https://pt.m-team.cc/torrentrss.php?https=1&rows=10&cat406=1&cat408=1&cat434=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://hdsky.me/torrentrss.php?rows=10&tea6=1&tea1=1&tea28=1&tea9=1&tea31=1&tea18=1&tea22=1&tea35=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://springsunday.net/torrentrss.php?rows=10&tea1=1&tea9=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://ourbits.club/torrentrss.php?rows=10&tea1=1&tea2=1&tea12=1&tea42=1&tea46=1&tea47=1&tea48=1&tea3=1&tea18=1&tea31=1&isize=1&passkey=xxxxxxxx&https=1&linktype=dl
          all_entries: no
    no_entries_ok: yes
    accept_all: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  reseed:
    priority: 1
    iyuu_auto_reseed:
      iyuu: xxxxxxxx
      passkeys:
        1ptba: xxxxxxxx
        52pt: xxxxxxxx
        beitai: xxxxxxxx
        brobits: xxxxxxxx
        btschool: xxxxxxxx
        discfan: xxxxxxxx
        eastgame: xxxxxxxx
        et8: xxxxxxxx
        haidan: xxxxxxxx
        hdarea: xxxxxxxx
        hdbd: xxxxxxxx
        hdcity:
          headers:
            cookie: 'xxxxxxxx'
            user-agent: '{? headers.user_agent ?}'
        hddisk: xxxxxxxx
        hddolby: xxxxxxxx
        hdhome: xxxxxxxx
        hdsky: xxxxxxxx
        hdstreet: xxxxxxxx
        hdtime: xxxxxxxx
        hdzone: xxxxxxxx
        joyhd: xxxxxxxx
        keepfrds: xxxxxxxx
        leaguehd: xxxxxxxx
        moecat: xxxxxxxx
        msg: xxxxxxxx
        m-team: xxxxxxxx
        nanyangpt: xxxxxxxx
        open: xxxxxxxx
        oshen: xxxxxxxx
        ourbits: xxxxxxxx
        pterclub: xxxxxxxx
        pthome: xxxxxxxx
        ptsbao: xxxxxxxx
        skyeysnow: xxxxxxxx
        springsunday: xxxxxxxx
        soulvoice: xxxxxxxx
        sjtu: xxxxxxxx
        tjupt: xxxxxxxx
        totheglory: xxxxxxxx
        yingk: xxxxxxxx
      qbittorrent_ressed:
        host: qbittorrent.example.com
        port: 443
        use_ssl: yes
        username: xxxxxxxx
        password: xxxxxxxx
    accept_all: yes
    no_entries_ok: yes
    seen:
      fields:
        - url
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
          skip_checking: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  resume:
    priority: 2
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_state == 'pausedUP' and qbittorrent_downloaded == 0 and qbittorrent_added_on > now - timedelta(hours=1): accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

  delete:
    priority: 3
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_category in ['Rss'] and qbittorrent_last_activity < now - timedelta(hours=2): accept
      - qbittorrent_state == 'missingFiles' or (qbittorrent_state in ['pausedDL'] and qbittorrent_completed == 0): accept
      - "'open' in qbittorrent_tags and (qbittorrent_seeding_time < 48*60*60 or qbittorrent_num_complete < 5) and not qbittorrent_state in ['pausedDL']": reject
    sort_by: qbittorrent_reseed_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_template

  modify:
    priority: 4
    disable: [seen, seen_info_hash, retry_failed]
    accept_all: yes
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template

  sign_in:
    auto_sign_in:
      user-agent: '{? headers.user_agent ?}'
      command_executor: 'http://selenium-chrome:4444/wd/hub'
      max_workers: 4
      aipocr:
        app_id: 'xxxxxxxx'
        api_key: 'xxxxxxxx'
        secret_key: 'xxxxxxxx'
      sites:
        1ptba: 'xxxxxxxx'
        52pt: 'xxxxxxxx'
        avgv: 'xxxxxxxx'
        beitai: 'xxxxxxxx'
        btschool: 'xxxxxxxx'
        crypt: 'xxxxxxxx'
        dhcmusic: 'xxxxxxxx'
        dicmusic: 'xxxxxxxx'
        discfan: 'xxxxxxxx'
        eastgame: 'xxxxxxxx'
        et8: 'xxxxxxxx'
        haidan: 'xxxxxxxx'
        hdarea: 'xxxxxxxx'
        hdbd: 'xxxxxxxx'
        hdcity: 'xxxxxxxx'
        hddolby: 'xxxxxxxx'
        hddisk: 'xxxxxxxx'
        hdfans: 'xxxxxxxx'
        hdhome: 'xxxxxxxx'
        hdpost:
          login:
            usernameOrEmail: 'xxxxxxxx'
            password: 'xxxxxxxx'
        hdsky: 'xxxxxxxx'
        hdstreet: 'xxxxxxxx'
        hdtime: 'xxxxxxxx'
        hdzone: 'xxxxxxxx'
        hitpt: 'xxxxxxxx'
        j99: 'xxxxxxxx'
        joyhd: 'xxxxxxxx'
        keepfrds: 'xxxxxxxx'
        lbj007: 'xxxxxxxx'
        leaguehd: 'xxxxxxxx'
        m-team:
          cookie: 'xxxxxxxx'
          secret_key: 'xxxxxxxx'
        moecat: 'xxxxxxxx'
        msg: 'xxxxxxxx'
        nanyangpt: 'xxxxxxxx'
        open: 'xxxxxxxx'
        oshen: 'xxxxxxxx'
        ourbits: 'xxxxxxxx'
        pterclub: 'xxxxxxxx'
        pthome: 'xxxxxxxx'
        ptsbao: 'xxxxxxxx'
        skyey2:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
        soulvoice: 'xxxxxxxx'
        springsunday: 'xxxxxxxx'
        sjtu: 'xxxxxxxx'
        totheglory: 'xxxxxxxx'
        tjupt: 'xxxxxxxx'
        wenyuan: 'xxxxxxxx'
        yingk: 'xxxxxxxx'
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: false
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {% for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- if entry.messages|d('') %}
          Messages: {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {% for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- if entry.messages|d('') %}
          Messages: {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
        via:
          - wechat_work:
              corp_id: 'xxxxxxxx'
              corp_secret: 'xxxxxxxx'
              agent_id: 'xxxxxxxx'
              to_user: 'xxxxxxxx'
          - telegram:
              bot_token: xxxxxxxx
              recipients:
                - username: 'xxxxxxxx'

  warner:
    disable: [seen, seen_info_hash, retry_failed]
    from_qbittorrent_mod:
      server_state: yes
    if:
      - 'server_state["free_space_on_disk"] < 5368709120': accept
    template:
      - from_qbittorrent_template
    notify:
      entries:
        message: "Title: {{title}}\nfree_space_on_disk: {{(server_state['free_space_on_disk']/1024/1024/1024)|int}} GiB"
        via:
          - wechat_work:
              corp_id: 'xxxxxxxx'
              corp_secret: 'xxxxxxxx'
              agent_id: 'xxxxxxxx'
              to_user: 'xxxxxxxx'
          - telegram:
              bot_token: xxxxxxxx
              recipients:
                - username: 'xxxxxxxx'
