web_server:
  bind: 0.0.0.0
  port: 3539

schedules:
  - tasks: [pterclub, totheglory, rss_download]
    interval:
      minutes: 1

  - tasks: [reseed, resume, delete, modify, clean]
    interval:
      minutes: 5

  - tasks: [opencd, springsunday, dmhy]
    interval:
      minutes: 10

  - tasks: [sign_in, warner]
    schedule:
      hour: 8-23/1

variables:
  headers:
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36'
  via: &via_setting
    - wechat_work:
        corp_id: 'xxxxxxxxxxxxx'
        corp_secret: 'xxxxxxxxxxxxxxxxxxx'
        agent_id: 'xxxxxxxxxxxx'
        to_user: 'xxxxxxxxxxx'
    - telegram:
        bot_token: xxxxxxxxxxxxx
        recipients:
          - username: 'xxxxxxxxxxxxxxxx'

templates:
  from_qbittorrent_template:
    from_qbittorrent_mod: &qbittorrent_setting
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: admin
      password: xxxxxxxxxxx

  qbittorrent_base_template:
    qbittorrent_mod: *qbittorrent_setting

  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: 8388608
          reject_on_dl_speed: 5242880
          category: Rss
          autoTMM: yes

  qbittorrent_resume_template:
    qbittorrent_mod:
      action:
        resume:
          recheck_torrents: yes

  qbittorrent_pause_template:
    qbittorrent_mod:
      action:
        pause: yes

  qbittorrent_delete_keeper_template:
    qbittorrent_mod:
      action:
        remove:
          keeper:
            check_reseed:
              - chdbits
              - totheglory
              - m-team
              - open
              - pterclub
              - springsunday
              - ourbits
              - hdsky
              - keepfrds
              - tjupt
              - skyey2
              - dmhy
            delete_files: yes
            keep_disk_space: 10
            dl_limit_on_succeeded: 0
            alt_dl_limit_on_succeeded: 8388608
            dl_limit_interval: 900

  qbittorrent_delete_cleaner_template:
    qbittorrent_mod:
      action:
        remove:
          cleaner:
            delete_files: yes

  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          tag_by_tracker: yes
          replace_trackers:
            'http://tracker.pterclub.com/announce?passkey=xxxxxxxxxxxxx': 'https://tracker.pterclub.com/announce?passkey=xxxxxxxxxxxxx'

  show_entry_template:
    show_entry:
      state: entries
      attribute: yes

tasks:
  pterclub:
    rss:
      url: https://pterclub.com/torrentrss.php?rows=10&cat413=1&tag_internal=yes&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxxxxxxx
      all_entries: no
      other_fields:
        - link
    no_entries_ok: yes
    if:
      - size > 1024 * 1024 and size < 20 * 1024 *1024: accept
    notify:
      entries:
        message: "Title: {{title}}\nLink: {{link}}"
        via: *via_setting
    qbittorrent_mod:
      action:
        add:
          category: PTer
          reject_on_dl_limit: no
          reject_on_dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  totheglory:
    rss:
      url: https://totheglory.im/putrss.php?par=xxxxxxxxxxxxxxxxxxxxxx
      all_entries: no
    no_entries_ok: yes
    limit_new: 1
    regexp:
      accept:
        - TTG
        - Wiki
      from: title
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  springsunday:
    html_rss:
      url: https://springsunday.net/torrents.php?incldead=0&spstate=4&pick=0&inclbookmarked=0&exclusive=0&search=&search_area=0&search_mode=0&sort=8&type=desc
      headers:
        cookie: 'xxxxxxxxxxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxxxxxxxxxxxxx'
      root_element_selector: '.torrents > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: '.pro_free2up'
          attribute: alt
        seeders:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
        leechers:
          element_selector: 'td:nth-child(8)'
          attribute: textContent
    no_entries_ok: yes
    limit_new: 1
    if:
      - leechers|int > 2 and seeders|int >0 and seeders|int < 3 and promotion: accept
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_speed: 6291456
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      #- show_entry_template

  opencd:
    html_rss:
      url: https://open.cd/torrents.php?spstate=2&seeders=3&sort=7&type=asc
      headers:
        cookie: 'xxxxxxxxxxxxxxxxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxxxxxxxxx'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'div[style="padding-bottom: 5px"] > img'
          attribute: alt
        progress:
          element_selector: '.progress_completed'
          attribute: class
    no_entries_ok: yes
    limit_new: 1
    if:
      - promotion in ['Free', '2X Free']: accept
      - "progress and 'progress_completed' not in progress": reject
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  dmhy:
    html_rss:
      url: https://u2.dmhy.org/torrents.php?sort=8&type=desc
      headers:
        cookie: 'xxxxxxxxxxxxxxxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxxxxxxxxxxx'
      root_element_selector: '#outer > table.main > tbody > tr > td > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: textContent
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro"]'
          attribute: alt
        promotion_time:
          element_selector: 'b > time'
          attribute: title
        upload_ratio:
          element_selector: 'img[alt="上传比率"] + b'
          attribute: textContent
        download_ratio:
          element_selector: 'img[alt="下载比率"] + b'
          attribute: textContent
        seeders:
          element_selector: 'td:nth-child(6)'
          attribute: textContent
        leechers:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
    no_entries_ok: yes
    limit_new: 1
    if:
      - promotion_time and promotion_time|parsedate < now + timedelta(hours=23): reject
      - upload_ratio == '2.33X' and download_ratio == '0.00X' and leechers|int > 5 and seeders|int >0 and seeders|int < 3: accept
      - promotion in ['2X Free'] and leechers|int > 5 and seeders|int >0 and seeders|int < 3: accept
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_speed: 6291456
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      - show_entry_template

  rss_download:
    inputs:
      - rss:
          url: https://www.skyey2.com/ptrss.php?id=xxxxxxxxx
          all_entries: no
      - rss:
          url: https://ourbits.club/torrentrss.php?rows=10&tea1=1&isize=1&passkey=xxxxxxxxxxxxxxxxxxx&https=1&linktype=dl
          all_entries: no
      - rss:
          url: https://chdbits.co/torrentrss.php?rows=10&tea14=1&tea13=1&tea1=1&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxxxxxx
          all_entries: no
      - rss:
          url: https://pt.keepfrds.com/torrentrss.php?rows=10&tea6=1&tea3=1&tea8=1&tea9=1&tea10=1&isize=1&linktype=dl&passkey=xxxxxxxxxxxx
          all_entries: no
      - rss:
          url: https://www.tjupt.org/torrentrss.php?rows=10&official=1&passkey=xxxxxxxxxxxxxxx&linktype=dl
          all_entries: no
      - rss:
          url: https://pt.m-team.cc/torrentrss.php?https=1&rows=10&tea9=1&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxxxx
          all_entries: no
      - rss:
          url: https://hdsky.me/torrentrss.php?rows=10&tea6=1&tea1=1&tea28=1&tea9=1&tea31=1&tea18=1&tea22=1&tea34=1&tea35=1&isize=1&linktype=dl&passkey=xxxxxxxxxxxx
          all_entries: no
      - rss:
          url: https://springsunday.net/torrentrss.php?rows=10&tea1=1&tea9=1&isize=1&https=1&linktype=dl&passkey=xxxxxxxxx
          all_entries: no
      - rss:
          url: https://open.cd/torrentrss.php?rows=10&isize=1&linktype=dl&passkey=xxxxxxxxxxxxxx
          all_entries: no
    no_entries_ok: yes
    accept_all: yes
    limit_new: 1
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  reseed:
    priority: 1
    plugin_priority:
      from_qbittorrent_mod: 250
      iyuu_auto_reseed: 240
    iyuu_auto_reseed:
      iyuu: xxxxxxxxxxxxx
      passkeys:
        1ptba: xxxxxxxxxxxxxxxxx
        52pt: xxxxxxxxxxxxxxxxx
        beitai: xxxxxxxxxxxxxxxxx
        brobits: xxxxxxxxxxxxxxxxx
        btschool: xxxxxxxxxxxxxxxxx
        chdbits: xxxxxxxxxxxxxxxxx
        dicmusic:
          authkey: xxxxxxxxxxxxxxxxx
          torrent_pass: xxxxxxxxxxxxxxxxx
        discfan: xxxxxxxxxxxxxxxxx
        dmhy: xxxxxxxxxxxxxxxxx
        eastgame: xxxxxxxxxxxxxxxxx
        et8: xxxxxxxxxxxxxxxxx
        haidan: xxxxxxxxxxxxxxxxx
        hd-torrents: xxxxxxxxxxxxxxxxx
        hd4fans: xxxxxxxxxxxxxxxxx
        hdarea: xxxxxxxxxxxxxxxxx
        hdbd: xxxxxxxxxxxxxxxxx
        hdcity:
          headers:
            cookie: xxxxxxxxxxxxxxxxx
            user-agent: '{? headers.user_agent ?}'
        hddisk: xxxxxxxxxxxxxxxxx
        hddolby: xxxxxxxxxxxxxxxxx
        hdfans: xxxxxxxxxxxxxxxxx
        hdhome: xxxxxxxxxxxxxxxxx
        hdsky: xxxxxxxxxxxxxxxxx
        hdstreet: xxxxxxxxxxxxxxxxx
        hdtime: xxxxxxxxxxxxxxxxx
        hdupt: xxxxxxxxxxxxxxxxx
        hdzone: xxxxxxxxxxxxxxxxx
        hitpt: xxxxxxxxxxxxxxxxx
        joyhd: xxxxxxxxxxxxxxxxx
        keepfrds: xxxxxxxxxxxxxxxxx
        leaguehd: xxxxxxxxxxxxxxxxx
        msg: xxxxxxxxxxxxxxxxx
        m-team: xxxxxxxxxxxxxxxxx
        nicept: xxxxxxxxxxxxxxxxx
        nanyangpt: xxxxxxxxxxxxxxxxx
        open: xxxxxxxxxxxxxxxxx
        oshen: xxxxxxxxxxxxxxxxx
        ourbits: xxxxxxxxxxxxxxxxx
        pterclub: xxxxxxxxxxxxxxxxx
        pthome: xxxxxxxxxxxxxxxxx
        ptsbao: xxxxxxxxxxxxxxxxx
        skyeysnow: xxxxxxxxxxxxxxxxx
        soulvoice: xxxxxxxxxxxxxxxxx
        springsunday: xxxxxxxxxxxxxxxxx
        sjtu: xxxxxxxxxxxxxxxxx
        tjupt: xxxxxxxxxxxxxxxxx
        totheglory: xxxxxxxxxxxxxxxxx
        yingk: xxxxxxxxxxxxxxxxx
    accept_all: yes
    no_entries_ok: yes
    seen:
      fields:
        - url
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: no
          reject_on_dl_speed: no
          skip_checking: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      - from_qbittorrent_template

  resume:
    priority: 2
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_state == 'pausedUP' and qbittorrent_downloaded == 0 and qbittorrent_added_on > now - timedelta(hours=1): accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

  delete:
    priority: 3
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_category in ['Rss'] and qbittorrent_last_activity < now - timedelta(hours=31): accept
      - qbittorrent_state == 'missingFiles' or (qbittorrent_state in ['pausedDL'] and qbittorrent_completed == 0): accept
      - "'open' in qbittorrent_tags and (qbittorrent_seeding_time < 48*60*60 or qbittorrent_num_complete < 5) and not qbittorrent_state in ['pausedDL']": reject
    sort_by: qbittorrent_reseed_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template

  modify:
    priority: 4
    disable: [seen, seen_info_hash, retry_failed]
    accept_all: yes
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template

  clean:
    priority: 5
    disable: [seen, seen_info_hash, retry_failed]
    regexp:
      accept:
        - '[Tt]orrent not registered with this tracker'
        - 'Torrent banned'
        - 'Unregistered torrent'
      from: qbittorrent_tracker_msg
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_cleaner_template

  sign_in:
    auto_sign_in:
      user-agent: '{? headers.user_agent ?}'
      max_workers: 1
      aipocr:
        app_id: 'xxxxxxxx'
        api_key: 'xxxxxxxxxxx'
        secret_key: 'xxxxxxxxxxxxxx'
      sites:
        qbittorrent:
          - name: qbittorrent
            host: qbittorrent.example.com
            port: 443
            use_ssl: yes
            username: admin
            password: xxxxxxxxxxxxxxx
        1ptba: 'xxxxxxxxxxxxxxxxx'
        52pt: 'xxxxxxxxxxxxxxxxx'
        avgv: 'xxxxxxxxxxxxxxxxx'
        beitai: 'xxxxxxxxxxxxxxxxx'
        btschool: 'xxxxxxxxxxxxxxxxx'
        chdbits: 'xxxxxxxxxxxxxxxxx'
        dhcmusic: 'xxxxxxxxxxxxxxxxx'
        dicmusic: 'xxxxxxxxxxxxxxxxx'
        discfan: 'xxxxxxxxxxxxxxxxx'
        dmhy:
          cookie: 'xxxxxxxxxxxxxxxxx'
          username: 'xxxxxxxxxxxxxxxxx'
          comment: 'xxxxxxxxxxxxxxxxx'
        eastgame: 'xxxxxxxxxxxxxxxxx'
        et8: 'xxxxxxxxxxxxxxxxx'
        filelist: 'xxxxxxxxxxxxxxxxx'
        gazellegames: 'xxxxxxxxxxxxxxxxx'
        haidan: 'xxxxxxxxxxxxxxxxx'
        hd-torrents: 'xxxxxxxxxxxxxxxxx'
        hd4fans: 'xxxxxxxxxxxxxxxxx'
        hdarea: 'xxxxxxxxxxxxxxxxx'
        hdatmos: 'xxxxxxxxxxxxxxxxx'
        hdbd: 'xxxxxxxxxxxxxxxxx'
        hdcity: 'xxxxxxxxxxxxxxxxx'
        hddolby: 'xxxxxxxxxxxxxxxxx'
        hddisk: 'xxxxxxxxxxxxxxxxx'
        hdfans: 'xxxxxxxxxxxxxxxxx'
        hdhome: 'xxxxxxxxxxxxxxxxx'
        hdpost:
          login:
            usernameOrEmail: 'xxxxxxxxxxxxxxxxx'
            password: 'xxxxxxxxxxxxxxxxx'
        hdsky: 'xxxxxxxxxxxxxxxxx'
        #hdstreet: 'xxxxxxxxxxxxxxxxx'
        hdtime: 'xxxxxxxxxxxxxxxxx'
        hdupt: 'xxxxxxxxxxxxxxxxx'
        hdzone: 'xxxxxxxxxxxxxxxxx'
        hitpt: 'xxxxxxxxxxxxxxxxx'
        joyhd: 'xxxxxxxxxxxxxxxxx'
        keepfrds: 'xxxxxxxxxxxxxxxxx'
        lbj007: 'xxxxxxxxxxxxxxxxx'
        leaguehd: 'xxxxxxxxxxxxxxxxx'
        m-team:
          login:
            username: 'xxxxxxxxxxxxxxxxx'
            password: 'xxxxxxxxxxxxxxxxx'
            secret_key: 'xxxxxxxxxxxxxxxxx'
        msg: 'xxxxxxxxxxxxxxxxx'
        nicept: 'xxxxxxxxxxxxxxxxx'
        nanyangpt: 'xxxxxxxxxxxxxxxxx'
        open: 'xxxxxxxxxxxxxxxxx'
        oshen: 'xxxxxxxxxxxxxxxxx'
        ourbits:
          login:
            username: 'xxxxxxxxxxxxxxxxx'
            password: 'xxxxxxxxxxxxxxxxx'
        pterclub: 'xxxxxxxxxxxxxxxxx'
        pthome: 'xxxxxxxxxxxxxxxxx'
        ptsbao: 'xxxxxxxxxxxxxxxxx'
        skyey2:
          login:
            username: 'xxxxxxxxxxxxxxxxx'
            password: 'xxxxxxxxxxxxxxxxx'
        soulvoice: 'xxxxxxxxxxxxxxxxx'
        springsunday: 'xxxxxxxxxxxxxxxxx'
        sjtu: 'xxxxxxxxxxxxxxxxx'
        totheglory: 'xxxxxxxxxxxxxxxxx'
        tjupt: 'xxxxxxxxxxxxxxxxx'
        #wenyuan: 'xxxxxxxxxxxxxxxxx'
        #yingk: 'xxxxxxxxxxxxxxxxx'
        suannai: 'xxxxxxxxxxxxxxxxx'
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: false
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }} Reason: {{entry.reason|d('unknown')}}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- for group in task.entries|groupby('task') %}
          {% for entry in group.list %}
          {%- if entry.messages|d('') %}
          Messages:
          {{ entry.title }} {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
        via:
          - wechat_work:
              corp_id: 'xxxxxxxxxxxxxxxxx'
              corp_secret: 'xxxxxxxxxxxxxxxxx'
              agent_id: 'xxxxxxxxxxxxxxxxx'
              to_user: 'xxxxxxxxxxxxxxxxx'
              image: 'xxxxxxxxxxxxxxxxx'
          - telegram:
              bot_token: 'xxxxxxxxxxxxxxxxx'
              recipients:
                - username: 'xxxxxxxxxxxxxxxxx'

  warner:
    disable: [seen, seen_info_hash, retry_failed]
    from_qbittorrent_mod:
      server_state: yes
    if:
      - 'not server_state["flexget_connected"]': accept
      - 'server_state["dl_info_speed"] < 1048576': accept
      - 'server_state["up_info_speed"] < 1048576': accept
      - 'server_state["free_space_on_disk"] < 5368709120': accept
    template:
      - from_qbittorrent_template
    notify:
      entries:
        message: |+
          {{ time }}
          qBittorrent Server State:
          {% if not server_state.flexget_connected -%}
          flexget_connected: False
          {%- else -%}
          dl_info_speed: {{(server_state['dl_info_speed']/1024/1024)|int}} MiB
          up_info_speed: {{(server_state['up_info_speed']/1024/1024)|int}} MiB
          free_space_on_disk: {{(server_state['free_space_on_disk']/1024/1024/1024)|int}} GiB
          {% endif %}
        via: *via_setting