web_server:
  bind: 0.0.0.0
  port: 3539

templates:
  qbittorrent_base_template:
    qbittorrent_mod:
      host: qbittorrent.example.com
      port: 443
      use_ssl: true
      username: admin
      password: 123456789xx

  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: 4194304
          category: Rss
          autoTMM: true

  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          tag_by_tracker: true
          replace_tracker:
            'http://tracker.pt1.com/announce.php?passkey=xxxxxxxxxxxxxx': 'https://tracker.pt1.com/announce.php?passkey=xxxxxxxxxxxxxx'

  qbittorrent_resume_template:
    qbittorrent_mod:
      action:
        resume:
          recheck_torrents: true

  qbittorrent_delete_template:
    qbittorrent_mod:
      action:
        remove:
          check_reseed: true
          delete_files: true
          keep_disk_space: 10
          dl_limit_on_succeeded: 0
          dl_limit_interval: 1800

  from_qbittorrent_template:
    from_qbittorrent_mod:
      host: qbittorrent.example.com
      port: 443
      use_ssl: true
      username: admin
      password: 123456789xx

schedules:
  - tasks: [rss1, rss2]
    interval:
      minutes: 1

  - tasks: [reseed, resume, delete, modify]
    interval:
      minutes: 5

  - tasks: [pt3]
    schedule:
      minute: 35
      hour: "*/3"

tasks:
  rss1:
    rss: https://pt1.com/rss
    regexp:
      accept:
        - CCTV
      from: title
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  rss2:
    inputs:
      - rss: https://pt1.com/rss
      - rss: https://pt2.com/rss
    accept_all: yes
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  pt3:
    html_rss:
      url: https://pt3.com/torrents.php
      headers:
        cookie: 'xxxxxxxxxxxxxxxxxx'
        user-agent: 'xxxxxxxxxx'
      passkey: xxxxxxxxxxxxx
      element_selector: '#form_torrent > table > tbody > tr.topdown_bg'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'div[style="padding-bottom: 5px"] > img'
          attribute: alt
    no_entries_ok: yes
    if:
      - promotion in ['Free']: accept
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  reseed:
    priority: 1
    iyuu_auto_reseed:
      iyuu: xxxxxxxxxxxxxxxxxxxx
      passkeys:
        pt123: xxxxxxxxxxxxxxxxxxxx
        abc456: xxxxxxxxxxxxxxxxxxxx
      qbittorrent_ressed:
        host: qbittorrent.example.com
        port: 443
        use_ssl: true
        username: admin
        password: 123456789xx
    accept_all: yes
    qbittorrent_mod:
      action:
        add:
          reject_on_dl_limit: 0
          skip_checking: true
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  resume:
    priority: 2
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_state == 'pausedUP' and qbittorrent_downloaded == 0: accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

  delete:
    priority: 3
    disable: [seen, seen_info_hash, retry_failed]
    if:
      - qbittorrent_category in ['Rss'] and qbittorrent_last_activity < now - timedelta(days=2): accept
      - qbittorrent_state == 'missingFiles' or (qbittorrent_state in ['pausedDL'] and qbittorrent_completed == 0): accept
      - "'pt1' in qbittorrent_tags and qbittorrent_seeding_time<48*60*60": reject
    sort_by: qbittorrent_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_template

  modify:
    priority: 4
    disable: [seen, seen_info_hash, retry_failed]
    accept_all: yes
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template
