version: '3.7'
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      WEBUI_PORT: 8080
    volumes:
      - <path for config files>:/config
      - <path for data files>:/downloads
    expose:
      - "8080"
    ports:
      - "60566:60566"
      - "60566:60566/udp"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
    networks:
      - nginx-network

  flexget:
    image: ivonwei/flexget
    container_name: flexget
    environment:
      FG_WEBUI_PASSWD: 12nfo34ivc043iv9
      FG_LOG_LEVEL: INFO
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
    volumes:
      - <path for config files>:/root/.flexget/config
      - <path for data files>:/downloads
    ports:
      - "3539:3539"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network
